services:
  app-server:
    image: app-server
    depends_on:
      - mosquitto
    ports:
      - "9191:9191"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "8883:8883"
      - "8884:8884"
      - "8885:8885"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/acl:/mosquitto/acl
      - ./cert:/mosquitto/cert
